version: '3.9'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_network

  yolo5:
    build:
      context: ./yolo5
    container_name: yolo5
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials directory (read-only)
    environment:
      AWS_REGION: us-east-1
      S3_BUCKET_NAME: netflix.jeenge  # Corrected bucket name
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network: