version: '3.9'

services:
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    networks:
      - mongoCluster
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "0.0.0.0"] # Removed mongo1
    volumes:
      - mongo1-data:/data/db # Using named volume
    environment:
      - MONGO_URI=${MONGO_URI} #Consider removing these environment variables from mongo containers
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    networks:
      - mongoCluster
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "0.0.0.0"] # Removed mongo2
    volumes:
      - mongo2-data:/data/db  # Using named volume
    environment:
      - MONGO_URI=${MONGO_URI}  #Consider removing these environment variables from mongo containers
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    networks:
      - mongoCluster
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "0.0.0.0"] # Removed mongo3
    volumes:
      - mongo3-data:/data/db  # Using named volume
    environment:
      - MONGO_URI=${MONGO_URI}  #Consider removing these environment variables from mongo containers
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}

  mongo-init:
    image: mongo:4.4
    container_name: mongo-init
    networks:
      - mongoCluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: >
      sh -c "
        sleep 10;
        mongo --host mongo1 --eval '
          rs.initiate({
            _id: \"myReplicaSet\",
            members: [
              {_id: 0, host: \"mongo1:27017\"},
              {_id: 1, host: \"mongo2:27017\"},
              {_id: 2, host: \"mongo3:27017\"}
            ]
          })
        ';
        "

  yolov5:
    image: jeenge/yolo5:1.0.1
    container_name: yolo5
    ports:
      - "8081:8081"
    environment:
      - S3_BUCKET_NAME=netflix.jeenge
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
      - MONGO_URI=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=myReplicaSet # Correct URI
      - MONGO_DB=default_db
      - MONGO_COLLECTION=predictions
    networks:
      - mongoCluster

  polybot-service:
    image: jeenge/polybot:1.0.1
    container_name: polybot
    platform: linux/amd64
    ports:
      - "8443:8443"
    environment:
      MONGO_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=myReplicaSet # Correct URI
      TELEGRAM_APP_URL: ${TELEGRAM_APP_URL}
      S3_BUCKET_NAME: ${BUCKET_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ~/.aws:/root/.aws
      - ./telegram_token.txt:/run/secrets/telegram_token
      - ./certs/cert.pem:/app/cert.pem
      - ./certs/key.pem:/app/key.pem
    depends_on:
      - yolov5
    networks:
      - mongoCluster

networks:
  mongoCluster:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: