name: Polybot Service Deployment

on:
  push:
    branches:
      - main # Trigger on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your-dockerhub-username/your-image-name:${{ github.run_id }}

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 13.49.46.43
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/jeenge/PolybotServiceDocker/yolo5
            docker-compose pull
            docker-compose up -d

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.1.5
        with:
          to: your_telegram_chat_id
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🎉 New version of Polybot deployed successfully!
            Commit: ${{ github.sha }}
            Build ID: ${{ github.run_id }}